twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        #path shortcuts
        adm_provider: '%adm_provider%'
        adm_ingredient: '%adm_ingredient%'
        adm_input: '%adm_input%'
        adm_allergy: Admin/Allergy/
        #domain: http://localhost:8000
        domain: http://v2.jphnovitz.be
        products: "@app.products"
        site: "@app.site"
        pdf_base: '%router.request_context.host%'
        pathToWeb: "%kernel.root_dir%/../public"
        pathToTemplate: "%kernel.root_dir%/../templates"

